# Generated by Django 3.1.7 on 2021-03-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210326_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media')),
                ('profession', models.CharField(max_length=50)),
                ('comment', models.TextField()),
            ],
        ),
    ]
